### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [smatsumt/parse-tokyo-covid-report-pdf#7]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/CDERGY
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by smatsumt** [comment]
Sure! I will update the dataset while original datasource (https://www.bousai.metro.tokyo.lg.jp/taisaku/saigai/1007261/index.html) is updated.

**Comment by k-goncharova** [comment]
Thank you, @smatsumt. It would be also helpful if you could add metadata like description and keywords to your dataset in Dataverse. Should take you no longer 10-15 mins, but it will make the dataset easier to identify and use for building COVID-19 knowledge graph. If you register in CoronaWhy Dataverse, we'll give you edit rights for your dataset https://datasets.coronawhy.org/
